window.VSC_AUTHORS = {
  "tran-anh-vu": { authorId:"tran-anh-vu", name:"ThS. NCS. Trần Anh Vũ", title:"Nhà sáng lập VSC Academy · Giảng viên dẫn dắt", bio:"Nghiên cứu, đào tạo và ứng dụng AI vào công việc, giáo dục và vận hành thực tế." },
  "vsc-editorial": { authorId:"vsc-editorial", name:"VSC Academy Editorial", title:"Ban biên tập VSC Academy", bio:"Chia sẻ kiến thức, phân tích và cập nhật về AI ứng dụng." }
};
window.VSC_ARTICLES = [
 {id:"art-001",slug:"ai-khong-thieu-cong-cu",title:"AI không thiếu công cụ. Cái thiếu là một cách làm việc với AI",excerpt:"Giá trị không nằm ở số lượng công cụ chúng ta biết, mà ở cách AI được tích hợp vào một hệ thống làm việc có mục tiêu và kiểm chứng.",contentType:"opinion",category:"goc-nhin",tags:["AI Literacy","Future of Work"],authorId:"tran-anh-vu",publishedAt:"2026-08-11",updatedAt:"2026-08-12",readingTime:8,featured:true,viewCount:1840,status:"published"},
 {id:"art-002",slug:"ai-agent-khac-gi-chatbot",title:"AI Agent khác gì chatbot và trợ lý AI?",excerpt:"Phân biệt ba cấp độ hỗ trợ của AI để lựa chọn đúng mô hình cho từng nhóm công việc.",contentType:"knowledge",category:"ai-agent",tags:["AI Agent","Automation"],authorId:"vsc-editorial",publishedAt:"2026-08-09",updatedAt:"2026-08-09",readingTime:7,featured:true,viewCount:1310,status:"published"},
 {id:"art-003",slug:"ai-ho-tro-giao-vien-o-dau",title:"AI nên hỗ trợ giáo viên ở đâu và dừng lại ở đâu?",excerpt:"Một góc nhìn cân bằng về hiệu quả, kiểm chứng và vai trò không thể thay thế của người dạy.",contentType:"opinion",category:"ai-giao-duc",tags:["AI Education","AI Literacy"],authorId:"tran-anh-vu",publishedAt:"2026-08-06",updatedAt:"2026-08-08",readingTime:9,featured:true,viewCount:1124,status:"published"},
 {id:"art-004",slug:"5-cach-dua-ai-vao-cong-viec",title:"5 cách đưa AI vào công việc mà không làm quy trình phức tạp",excerpt:"Bắt đầu từ những điểm có giá trị rõ ràng, ít rủi ro và đủ dễ để duy trì hằng ngày.",contentType:"knowledge",category:"ai-ung-dung",tags:["Productivity","AI"],authorId:"vsc-editorial",publishedAt:"2026-08-04",updatedAt:"2026-08-04",readingTime:6,featured:false,viewCount:985,status:"published"},
 {id:"art-005",slug:"tu-prompt-den-quy-trinh",title:"Từ prompt tốt đến một quy trình AI có thể lặp lại",excerpt:"Prompt chỉ là một thành phần. Quy trình còn cần dữ liệu đầu vào, điểm kiểm chứng và tiêu chuẩn đầu ra.",contentType:"knowledge",category:"nang-suat",tags:["Prompting","Workflow"],authorId:"tran-anh-vu",publishedAt:"2026-07-30",updatedAt:"2026-08-02",readingTime:10,featured:false,viewCount:842,status:"published"},
 {id:"art-006",slug:"tim-kiem-thong-tin-dang-thay-doi",title:"Cách con người tìm kiếm thông tin đang thay đổi cùng AI",excerpt:"Từ danh sách liên kết sang câu trả lời tổng hợp: cơ hội và rủi ro mới trong hành vi tìm kiếm.",contentType:"knowledge",category:"xu-huong",tags:["Future of Work","AI"],authorId:"vsc-editorial",publishedAt:"2026-07-26",updatedAt:"2026-07-29",readingTime:8,featured:false,viewCount:756,status:"published"},
 {id:"news-001",slug:"cap-nhat-workshop-ai-agent-thang-8",title:"VSC Academy cập nhật lịch workshop AI Agent tháng 8",excerpt:"Các phiên thực hành mới dành cho người muốn bắt đầu xây AI Agent cá nhân.",contentType:"academy_update",category:"tin-vsc",tags:["Workshop","AI Agent"],authorId:"vsc-editorial",publishedAt:"2026-08-13",updatedAt:"2026-08-13",lastVerifiedAt:"2026-08-13",readingTime:3,featured:false,viewCount:420,status:"published"},
 {id:"news-002",slug:"thay-doi-he-sinh-thai-ai-tuan-nay",title:"Những thay đổi đáng chú ý trong hệ sinh thái AI tuần này",excerpt:"Tóm lược những cập nhật công nghệ có khả năng ảnh hưởng đến công việc thực tế.",contentType:"news",category:"xu-huong",tags:["AI News","Technology"],authorId:"vsc-editorial",publishedAt:"2026-08-10",updatedAt:"2026-08-10",lastVerifiedAt:"2026-08-10",readingTime:4,featured:false,viewCount:603,status:"published"},
 {id:"news-003",slug:"ai-trong-giao-duc-tu-cong-cu-den-nang-luc",title:"Ứng dụng AI vào giáo dục: từ công cụ đến năng lực",excerpt:"Hoạt động chia sẻ chuyên môn về cách đưa AI vào dạy và học có hệ thống.",contentType:"academy_update",category:"tin-vsc",tags:["Hoạt động","AI Education"],authorId:"vsc-editorial",publishedAt:"2026-08-07",updatedAt:"2026-08-07",lastVerifiedAt:"2026-08-07",readingTime:3,featured:false,viewCount:388,status:"published"}
];
window.VSC_ARTICLE_CATEGORIES={"ai-ung-dung":"AI ứng dụng","ai-agent":"AI Agent & Automation","ai-giao-duc":"AI trong Giáo dục","nang-suat":"Năng suất & Công việc","goc-nhin":"Góc nhìn","xu-huong":"Xu hướng AI","tin-vsc":"Tin VSC Academy"};
