const header=document.querySelector('#header'),toggle=document.querySelector('.menu-toggle'),mobileNav=document.querySelector('.mobile-nav');
toggle?.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileNav.classList.remove('open')));
const I=window.VSC_I18N||{locale:'vi',root:''};const T=window.VSC_T||window.VSC_UI?.vi||{};const siteRoot=I.root||'';
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const events=[...(window.VSC_SCHEDULES||[])].sort((a,b)=>a.date.localeCompare(b.date));const grid=document.querySelector('#scheduleGrid'),agenda=document.querySelector('#scheduleAgenda'),panel=document.querySelector('#selectedClass'),empty=document.querySelector('#scheduleEmpty'),monthLabel=document.querySelector('#scheduleMonth'),yearLabel=document.querySelector('#scheduleYear'),calendar=document.querySelector('.schedule-calendar');let activeFilter='all',selected=null;const queryParams=new URLSearchParams(location.search),querySlug=queryParams.get('event'),queryProgram=queryParams.get('program');const queryEvent=events.find(e=>e.slug===querySlug),queryProgramEvent=events.find(e=>e.programId===queryProgram);let viewDate=queryEvent?new Date(`${queryEvent.date}T12:00:00`):queryProgramEvent?new Date(`${queryProgramEvent.date}T12:00:00`):new Date(2026,7,1);
const pad=n=>String(n).padStart(2,'0'),formatDate=e=>{const[y,m,d]=e.date.split('-');return`${d} · ${m} · ${y}`},statusLabel=e=>(T.status&&T.status[e.status])||(e.status==='full'?'Đã đầy':e.status==='limited'?'Sắp hết chỗ':e.status==='upcoming'?'Sắp mở':'Còn chỗ'),matches=e=>(!queryProgram||e.programId===queryProgram)&&(activeFilter==='all'||e.type===activeFilter||e.format===activeFilter||(activeFilter==='available'&&!['full','ended'].includes(e.status)));
const heroFeed=document.querySelector('#scheduleHeroFeed'),heroCounter=document.querySelector('#scheduleHeroCounter'),heroFeedBox=document.querySelector('.schedule-hero-feed');
if(heroFeed&&events.length){
  const feedEvents=events.filter(e=>e.status!=='ended'&&(!queryProgram||e.programId===queryProgram)).slice(0,5),reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)');let feedIndex=0,feedTimer;
  heroFeed.innerHTML=feedEvents.map((e,index)=>`<button class="schedule-hero-feed-item${index===0?' active':''}" type="button" data-hero-event="${e.slug}"><time datetime="${e.date}"><b>${e.date.slice(8)}</b><span>${(T.monthShort&&T.monthShort[Number(e.date.slice(5,7))-1])||('THG '+e.date.slice(5,7))}</span></time><span class="hero-feed-copy"><small>${e.type==='workshop'?'WORKSHOP':(T.course||'KHÓA HỌC').toUpperCase()} · ${e.format==='online'?'ONLINE':'OFFLINE'}</small><strong>${e.title}</strong><em>${e.startTime} – ${e.endTime} · ${statusLabel(e)}</em></span><i aria-hidden="true">↗</i></button>`).join('');
  const feedItems=[...heroFeed.querySelectorAll('.schedule-hero-feed-item')];const showFeed=index=>{feedIndex=(index+feedItems.length)%feedItems.length;feedItems.forEach((item,i)=>item.classList.toggle('active',i===feedIndex));heroFeed.style.transform=`translate3d(0,calc(${feedIndex} * -104px),0)`;if(heroCounter)heroCounter.textContent=`${pad(feedIndex+1)} / ${pad(feedItems.length)}`};const startFeed=()=>{clearInterval(feedTimer);if(!reduceMotion.matches&&feedItems.length>1)feedTimer=setInterval(()=>showFeed(feedIndex+1),3600)};
  feedItems.forEach((item,index)=>item.addEventListener('click',()=>{const e=events.find(event=>event.slug===item.dataset.heroEvent);viewDate=new Date(`${e.date}T12:00:00`);render();showEvent(e);document.querySelector('#calendar').scrollIntoView({behavior:'smooth'});showFeed(index);startFeed()}));heroFeedBox?.addEventListener('mouseenter',()=>clearInterval(feedTimer));heroFeedBox?.addEventListener('mouseleave',startFeed);reduceMotion.addEventListener?.('change',startFeed);showFeed(0);startFeed();
}
function showEvent(e,updateUrl=true){selected=e;panel.innerHTML=`<div class="panel-eyebrow"><span>${(T.selectedClass||'Lớp đang chọn').toUpperCase()}</span><i></i></div><p class="panel-date">${formatDate(e)}</p><span class="panel-category">${e.type==='workshop'?'WORKSHOP':(T.course||'KHÓA HỌC').toUpperCase()} · ${(e.formatLabel||e.format).toUpperCase()}</span><h3>${e.title}</h3><p class="panel-description">${e.description}</p><dl><div><dt>${T.time||'Thời gian'}</dt><dd>${e.startTime} – ${e.endTime}</dd></div><div><dt>${T.format||'Hình thức'}</dt><dd>${e.formatLabel||(e.format==='online'?(T.online||'Online'):(T.offline||'Offline'))}</dd></div>${e.durationLabel?`<div><dt>${T.duration||'Thời lượng'}</dt><dd>${e.durationLabel} · ${e.totalDuration}</dd></div>`:''}${e.scheduleLabel?`<div><dt>${T.schedule||'Lịch chính'}</dt><dd>${e.scheduleLabel}</dd></div>`:''}<div><dt>${T.platform||'Nền tảng'}</dt><dd>${e.location}</dd></div><div><dt>${T.tuition||'Học phí'}</dt><dd>${e.price}</dd></div>${e.supportLabel?`<div><dt>${T.supportAfter||'Hỗ trợ sau khóa'}</dt><dd>${e.supportLabel}</dd></div>`:''}</dl><a class="button" href="${siteRoot}${e.registrationUrl}">${e.status==='full'?(T.waitlist||'THAM GIA DANH SÁCH CHỜ').toUpperCase():e.status==='upcoming'?(T.notifyWhenOpen||'NHẬN THÔNG BÁO KHI MỞ LỚP').toUpperCase():(T.registerThisClass||'ĐĂNG KÝ LỚP NÀY').toUpperCase()+' →'}</a><a class="panel-detail" href="${siteRoot}${e.detailUrl}">${T.viewProgram||'Xem chi tiết chương trình'} →</a>`;document.querySelectorAll('[data-event]').forEach(el=>el.classList.toggle('selected',el.dataset.event===e.slug));if(updateUrl)history.replaceState({},'',`?event=${e.slug}`)}
function render(){const y=viewDate.getFullYear(),m=viewDate.getMonth(),prefix=`${y}-${pad(m+1)}`,monthEvents=events.filter(e=>e.date.startsWith(prefix)&&matches(e));yearLabel.textContent=y;monthLabel.textContent=T.monthTitle?T.monthTitle(m+1,y):`THÁNG ${pad(m+1)} · ${y}`;grid.innerHTML='';const offset=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();for(let i=0;i<offset;i++)grid.insertAdjacentHTML('beforeend','<span class="schedule-day is-empty"></span>');for(let d=1;d<=total;d++){const dayEvents=monthEvents.filter(e=>e.date===`${prefix}-${pad(d)}`);const cell=document.createElement('div');cell.className='schedule-day';cell.innerHTML=`<span>${pad(d)}</span>${dayEvents.slice(0,2).map(e=>`<button class="schedule-event ${e.type} ${e.format}" data-event="${e.slug}">${e.shortTitle}</button>`).join('')}${dayEvents.length>2?`<small class="schedule-more">+${dayEvents.length-2} ${T.otherClasses||'lớp khác'}</small>`:''}`;grid.appendChild(cell)}agenda.innerHTML=monthEvents.map(e=>`<article class="schedule-agenda-item"><strong>${e.date.slice(8)}<small> ${(T.monthShort&&T.monthShort[Number(e.date.slice(5,7))-1])||('THG '+e.date.slice(5,7))}</small></strong><div><h3>${e.title}</h3><p>${e.startTime} – ${e.endTime} · ${e.formatLabel||(e.format==='online'?'Online':'Offline')} · ${statusLabel(e)}</p></div><button data-event="${e.slug}" aria-label="Xem ${e.title}">→</button></article>`).join('');empty.hidden=monthEvents.length>0;grid.hidden=monthEvents.length===0;agenda.hidden=monthEvents.length===0;document.querySelectorAll('[data-event]').forEach(btn=>btn.addEventListener('click',()=>showEvent(events.find(e=>e.slug===btn.dataset.event))));const preferred=selected&&monthEvents.includes(selected)?selected:monthEvents.find(e=>e.status!=='full')||monthEvents[0];if(preferred)showEvent(preferred,false)}
document.querySelectorAll('.schedule-filterbar>button[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.schedule-filterbar>button[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;render()}));document.querySelector('#schedulePrev').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};document.querySelector('#scheduleNext').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};document.querySelector('#scheduleToday').onclick=()=>{viewDate=new Date(2026,7,1);render()};document.querySelector('#scheduleEmptyNext').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');calendar.classList.toggle('view-month',btn.dataset.view==='month')}));
if(queryEvent)selected=queryEvent;render();
