const header=document.querySelector('#header'),toggle=document.querySelector('.menu-toggle'),mobileNav=document.querySelector('.mobile-nav');
toggle?.addEventListener('click',()=>{const open=mobileNav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileNav.classList.remove('open')));
const I=window.VSC_I18N||{locale:'vi',root:''};const T=window.VSC_T||window.VSC_UI?.vi||{};const siteRoot=I.root||'';
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const events=[...(window.VSC_SCHEDULES||[])].sort((a,b)=>a.date.localeCompare(b.date));const grid=document.querySelector('#scheduleGrid'),agenda=document.querySelector('#scheduleAgenda'),panel=document.querySelector('#selectedClass'),empty=document.querySelector('#scheduleEmpty'),monthLabel=document.querySelector('#scheduleMonth'),yearLabel=document.querySelector('#scheduleYear'),calendar=document.querySelector('.schedule-calendar');let activeFilter='all',selected=null;const queryParams=new URLSearchParams(location.search),querySlug=queryParams.get('event'),queryProgram=queryParams.get('program'),queryDate=queryParams.get('date');const queryProgramEvent=events.find(e=>e.programId===queryProgram);
const pad=n=>String(n).padStart(2,'0'),sessionLabel=n=>I.locale==='en'?`Session ${n}`:`Buổi ${n}`,meetingList=e=>(Array.isArray(e.meetings)?e.meetings:[]).filter(m=>m&&m.date),statusLabel=e=>(T.status&&T.status[e.status])||(e.status==='full'?'Đã đầy':e.status==='limited'?'Sắp hết chỗ':e.status==='upcoming'?'Sắp mở':'Còn chỗ'),matches=e=>(!queryProgram||e.programId===queryProgram)&&(activeFilter==='all'||e.type===activeFilter||e.format===activeFilter||(activeFilter==='available'&&!['full','ended'].includes(e.status)));
const WEEKDAYS=I.locale==='en'?['Sun','Mon','Tue','Wed','Thu','Fri','Sat']:['Chủ nhật','Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7'];
const slashDate=iso=>{const[y,m,d]=String(iso||'').split('-');return y&&m&&d?`${d}/${m}/${y}`:''};
const weekdayOf=iso=>WEEKDAYS[new Date(`${iso}T12:00:00`).getDay()]||'';
const occurrences=events.flatMap(e=>{
  const meetings=meetingList(e);
  const rows=meetings.length?meetings:[{date:e.date,startTime:e.startTime,endTime:e.endTime}];
  return rows.map((m,i)=>({...e,date:m.date,startTime:m.startTime||m.start_time||e.startTime,endTime:m.endTime||m.end_time||e.endTime,meetingIndex:meetings.length>1?i+1:null,occurrenceId:`${e.slug}:${m.date}`}));
}).sort((a,b)=>a.date.localeCompare(b.date)||String(a.startTime||'').localeCompare(String(b.startTime||'')));
const formatDate=e=>{const[y,m,d]=e.date.split('-');const base=`${d} · ${m} · ${y}`;return e.meetingIndex?`${base} — ${sessionLabel(e.meetingIndex)}`:base};
const scheduleMainHtml=e=>{
  const meetings=meetingList(e);
  if(meetings.length>=2){
    return meetings.map((m,i)=>`+${weekdayOf(m.date)}: ${slashDate(m.date)} — ${sessionLabel(i+1)} | ${m.startTime||m.start_time||e.startTime}–${m.endTime||m.end_time||e.endTime}`).join('<br>');
  }
  return e.scheduleLabel||'';
};
const findOccurrence=(slug,date)=>occurrences.find(o=>o.slug===slug&&(!date||o.date===date))||occurrences.find(o=>o.slug===slug);
const queryOccurrence=querySlug?findOccurrence(querySlug,queryDate):null;
let viewDate=queryOccurrence?new Date(`${queryOccurrence.date}T12:00:00`):queryProgramEvent?new Date(`${queryProgramEvent.date}T12:00:00`):new Date(2026,7,1);
const heroFeed=document.querySelector('#scheduleHeroFeed'),heroCounter=document.querySelector('#scheduleHeroCounter'),heroFeedBox=document.querySelector('.schedule-hero-feed');
if(heroFeed&&events.length){
  const feedEvents=events.filter(e=>e.status!=='ended'&&(!queryProgram||e.programId===queryProgram)).slice(0,5),reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)');let feedIndex=0,feedTimer;
  heroFeed.innerHTML=feedEvents.map((e,index)=>`<button class="schedule-hero-feed-item${index===0?' active':''}" type="button" data-hero-event="${e.slug}"><time datetime="${e.date}"><b>${e.date.slice(8)}</b><span>${(T.monthShort&&T.monthShort[Number(e.date.slice(5,7))-1])||('THG '+e.date.slice(5,7))}</span></time><span class="hero-feed-copy"><small>${e.type==='workshop'?'WORKSHOP':(T.course||'KHÓA HỌC').toUpperCase()} · ${e.format==='online'?'ONLINE':'OFFLINE'}</small><strong>${e.title}</strong><em>${e.startTime} – ${e.endTime} · ${statusLabel(e)}</em></span><i aria-hidden="true">↗</i></button>`).join('');
  const feedItems=[...heroFeed.querySelectorAll('.schedule-hero-feed-item')];const showFeed=index=>{feedIndex=(index+feedItems.length)%feedItems.length;feedItems.forEach((item,i)=>item.classList.toggle('active',i===feedIndex));heroFeed.style.transform=`translate3d(0,calc(${feedIndex} * -104px),0)`;if(heroCounter)heroCounter.textContent=`${pad(feedIndex+1)} / ${pad(feedItems.length)}`};const startFeed=()=>{clearInterval(feedTimer);if(!reduceMotion.matches&&feedItems.length>1)feedTimer=setInterval(()=>showFeed(feedIndex+1),3600)};
  feedItems.forEach((item,index)=>item.addEventListener('click',()=>{const o=findOccurrence(item.dataset.heroEvent);viewDate=new Date(`${o.date}T12:00:00`);render();showEvent(o);document.querySelector('#calendar').scrollIntoView({behavior:'smooth'});showFeed(index);startFeed()}));heroFeedBox?.addEventListener('mouseenter',()=>clearInterval(feedTimer));heroFeedBox?.addEventListener('mouseleave',startFeed);reduceMotion.addEventListener?.('change',startFeed);showFeed(0);startFeed();
}
function showEvent(e,updateUrl=true){selected=e;const scheduleHtml=scheduleMainHtml(e);panel.innerHTML=`<div class="panel-eyebrow"><span>${(T.selectedClass||'Lớp đang chọn').toUpperCase()}</span><i></i></div><p class="panel-date">${formatDate(e)}</p><span class="panel-category">${e.type==='workshop'?'WORKSHOP':(T.course||'KHÓA HỌC').toUpperCase()} · ${(e.formatLabel||e.format).toUpperCase()}</span><h3>${e.title}</h3><p class="panel-description">${e.description}</p><dl>${e.slug?`<div><dt>${T.classCode||'Mã lớp'}</dt><dd class="panel-class-code">${e.slug}</dd></div>`:''}${e.instructorName?`<div><dt>${T.instructor||'Giảng viên'}</dt><dd>${e.instructorName}</dd></div>`:''}<div><dt>${T.time||'Thời gian'}</dt><dd>${e.startTime} – ${e.endTime}</dd></div><div><dt>${T.format||'Hình thức'}</dt><dd>${e.formatLabel||(e.format==='online'?(T.online||'Online'):(T.offline||'Offline'))}</dd></div>${e.durationLabel?`<div><dt>${T.duration||'Thời lượng'}</dt><dd>${e.durationLabel} · ${e.totalDuration}</dd></div>`:''}${scheduleHtml?`<div><dt>${T.schedule||'Lịch chính'}</dt><dd class="panel-schedule">${scheduleHtml}</dd></div>`:''}<div><dt>${T.platform||'Nền tảng'}</dt><dd>${e.location}</dd></div><div><dt>${T.tuition||'Học phí'}</dt><dd>${e.price}</dd></div>${e.supportLabel?`<div><dt>${T.supportAfter||'Hỗ trợ sau khóa'}</dt><dd>${e.supportLabel}</dd></div>`:''}</dl><a class="button" href="${siteRoot}${e.registrationUrl}">${e.status==='full'?(T.waitlist||'THAM GIA DANH SÁCH CHỜ').toUpperCase():e.status==='upcoming'?(T.notifyWhenOpen||'NHẬN THÔNG BÁO KHI MỞ LỚP').toUpperCase():(T.registerThisClass||'ĐĂNG KÝ LỚP NÀY').toUpperCase()+' →'}</a><a class="panel-detail" href="${siteRoot}${e.detailUrl}">${T.viewProgram||'Xem chi tiết chương trình'} →</a>`;document.querySelectorAll('[data-occurrence]').forEach(el=>el.classList.toggle('selected',el.dataset.occurrence===e.occurrenceId));if(updateUrl)history.replaceState({},'',`?event=${e.slug}${e.date?`&date=${e.date}`:''}`)}
function render(){const y=viewDate.getFullYear(),m=viewDate.getMonth(),prefix=`${y}-${pad(m+1)}`,monthEvents=occurrences.filter(e=>e.date.startsWith(prefix)&&matches(e));yearLabel.textContent=y;monthLabel.textContent=T.monthTitle?T.monthTitle(m+1,y):`THÁNG ${pad(m+1)} · ${y}`;grid.innerHTML='';const offset=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate();for(let i=0;i<offset;i++)grid.insertAdjacentHTML('beforeend','<span class="schedule-day is-empty"></span>');for(let d=1;d<=total;d++){const dayEvents=monthEvents.filter(e=>e.date===`${prefix}-${pad(d)}`);const cell=document.createElement('div');cell.className='schedule-day';cell.innerHTML=`<span>${pad(d)}</span>${dayEvents.slice(0,2).map(e=>`<button class="schedule-event ${e.type} ${e.format}" data-event="${e.slug}" data-occurrence="${e.occurrenceId}">${e.shortTitle}${e.meetingIndex?` · ${sessionLabel(e.meetingIndex)}`:''}</button>`).join('')}${dayEvents.length>2?`<small class="schedule-more">+${dayEvents.length-2} ${T.otherClasses||'lớp khác'}</small>`:''}`;grid.appendChild(cell)}agenda.innerHTML=monthEvents.map(e=>`<article class="schedule-agenda-item"><strong>${e.date.slice(8)}<small> ${(T.monthShort&&T.monthShort[Number(e.date.slice(5,7))-1])||('THG '+e.date.slice(5,7))}</small></strong><div><h3>${e.title}${e.meetingIndex?` · ${sessionLabel(e.meetingIndex)}`:''}</h3><p>${e.startTime} – ${e.endTime} · ${e.formatLabel||(e.format==='online'?'Online':'Offline')} · ${statusLabel(e)}</p></div><button data-event="${e.slug}" data-occurrence="${e.occurrenceId}" aria-label="Xem ${e.title}">→</button></article>`).join('');empty.hidden=monthEvents.length>0;grid.hidden=monthEvents.length===0;agenda.hidden=monthEvents.length===0;document.querySelectorAll('[data-occurrence]').forEach(btn=>btn.addEventListener('click',()=>showEvent(occurrences.find(e=>e.occurrenceId===btn.dataset.occurrence))));const preferred=selected&&monthEvents.find(e=>e.occurrenceId===selected.occurrenceId)||monthEvents.find(e=>e.status!=='full')||monthEvents[0];if(preferred)showEvent(preferred,false)}
document.querySelectorAll('.schedule-filterbar>button[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.schedule-filterbar>button[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;render()}));document.querySelector('#schedulePrev').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};document.querySelector('#scheduleNext').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};document.querySelector('#scheduleToday').onclick=()=>{viewDate=new Date(2026,7,1);render()};document.querySelector('#scheduleEmptyNext').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');calendar.classList.toggle('view-month',btn.dataset.view==='month')}));
if(queryOccurrence)selected=queryOccurrence;render();
