(()=>{const I=window.VSC_I18N||{locale:"vi",root:""};const T=window.VSC_T||window.VSC_UI?.vi||{};
const articleHref=slug=>I.href?I.href("article",`?article=${slug}`):`/bai-viet?article=${slug}`;
const rows=(window.VSC_ARTICLES||[]).filter(x=>x.status==="published"&&(I.locale!=="en"||x.titleEn||x.titleVi!==x.title)),authors=window.VSC_AUTHORS||{},cats=window.VSC_ARTICLE_CATEGORIES||{};let category="all";const $=s=>document.querySelector(s),fmt=d=>new Intl.DateTimeFormat(T.dateLocale||"vi-VN").format(new Date(d));
const cover=a=>`<a class="story-cover cover-${a.category}" href="${articleHref(a.slug)}" aria-label="${T.readArticle||"Đọc"} ${a.title}"><i></i><span>${cats[a.category]}</span><b>VSC<br>EDITORIAL</b></a>`;
const card=(a,cls="")=>`<article class="story-card ${cls}">${cover(a)}<div class="story-copy"><small>${cats[a.category]}</small><h3><a href="${articleHref(a.slug)}">${a.title}</a></h3><p>${a.excerpt}</p><div class="story-meta"><span>${authors[a.authorId]?.name||"VSC Academy"}</span><span>${fmt(a.publishedAt)} · ${T.readingTime?T.readingTime(a.readingTime):a.readingTime+" phút"}</span></div><a class="story-link" href="${articleHref(a.slug)}">${T.readArticle||"Đọc bài viết"} <b>→</b></a></div></article>`;
function featured(){const f=rows.filter(x=>x.featured).slice(0,3);$("#featuredMain").innerHTML=f[0]?card(f[0],"main-story"):"";$("#featuredSide").innerHTML=f.slice(1).map(x=>card(x,"side-story")).join("")}
function render(){const q=($("#articleSearch").value||"").toLocaleLowerCase("vi"),knowledge=rows.filter(x=>["knowledge","opinion"].includes(x.contentType)).filter(x=>(category==="all"||x.category===category)&&[x.title,x.excerpt,cats[x.category],...(x.tags||[]),authors[x.authorId]?.name].join(" ").toLocaleLowerCase("vi").includes(q)).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt));$("#articleGrid").innerHTML=knowledge.map(x=>card(x)).join("");$("#articleEmpty").hidden=knowledge.length>0;$("#articleCount").textContent=`${String(knowledge.length).padStart(2,"0")} ${(T.articles||"BÀI VIẾT").toUpperCase()}`;}
function news(){const n=rows.filter(x=>["news","academy_update"].includes(x.contentType)).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,6);$("#newsStream").innerHTML=n.map(x=>`<article><time>${fmt(x.publishedAt)}</time><small>${cats[x.category]}</small><div><h3><a href="${articleHref(x.slug)}">${x.title}</a></h3><p>${x.excerpt}</p></div><a href="${articleHref(x.slug)}" aria-label="${T.readArticle||"Đọc bài"}">→</a></article>`).join("")}
document.querySelector("[data-categories]")?.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;category=b.dataset.value;document.querySelectorAll("[data-categories] button").forEach(x=>x.classList.toggle("active",x===b));render()});$("#articleSearch").addEventListener("input",render);$("#resetArticles")?.addEventListener("click",()=>{$("#articleSearch").value="";category="all";document.querySelectorAll("[data-categories] button").forEach((x,i)=>x.classList.toggle("active",i===0));render()});document.querySelector(".menu-toggle")?.addEventListener("click",e=>{const n=document.querySelector(".mobile-nav"),o=n.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",String(o))});const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(x=>obs.observe(x));featured();render();news()})();
